# -------------------------------------------------------------------
# extend database with parameter names, descriptions and units
#
# This script belongs to software collection for persuasion analysis,
# provided by Technology Agency of the Czech Republic TACR TJ02000293
#
# 2019 - 2021, Brno University of Technology, janouseko@vut.cz
# -------------------------------------------------------------------

# -*- coding: utf-8 -*-

import pickle
import numpy as np
from constants import *

# open database
with open(DB_FILEPATH+r'\db.pickle', 'rb') as f:
    db = pickle.load(f)

# add parameter names, descriptions and units
for i in db['subject'].keys():
    # add parameter names
    # add parameter names in record
    db['subject'][i]['record']['timestamp']['name'] = 'time'
    db['subject'][i]['record']['res']['name'] = 'respiration'
    db['subject'][i]['record']['res_amp']['name'] = 'resp. amplitude'
    db['subject'][i]['record']['res_freq']['name'] = 'resp. frequency'
    db['subject'][i]['record']['temp_head']['name'] = 'head temperature'
    db['subject'][i]['record']['temp_hand']['name'] = 'hand temperature'
    db['subject'][i]['record']['temp_ear']['name'] = 'ear temperature'
    db['subject'][i]['record']['hr']['name'] = 'heart rate'
    db['subject'][i]['record']['eeg_tp9']['name'] = 'EEG TP9'
    db['subject'][i]['record']['eeg_af7']['name'] = 'EEG AF7'
    db['subject'][i]['record']['eeg_af8']['name'] = 'EEG AF8'
    db['subject'][i]['record']['eeg_tp10']['name'] = 'EEG TP10'
    db['subject'][i]['record']['acc_x']['name'] = 'forward/backward acc.'
    db['subject'][i]['record']['acc_y']['name'] = 'left/right acc.'
    db['subject'][i]['record']['acc_z']['name'] = 'up/down acc.'
    db['subject'][i]['record']['gyro_x']['name'] = 'roll'
    db['subject'][i]['record']['gyro_y']['name'] = 'pitch'
    db['subject'][i]['record']['gyro_z']['name'] = 'yaw'
    db['subject'][i]['record']['arousal']['name'] = 'arousal'
    db['subject'][i]['record']['valence']['name'] = 'valence'
    db['subject'][i]['record']['marker']['name'] = 'marker'
    # add parameter names in signal
    db['subject'][i]['signal']['hr_smooth']['name'] = 'heart rate'
    db['subject'][i]['signal']['hr_smooth_derivation']['name'] = 'speed of HR changes'
    db['subject'][i]['signal']['res_volume']['name'] = 'respiratory volume'
    db['subject'][i]['signal']['acc_mag']['name'] = 'magnitude of acc.'
    db['subject'][i]['signal']['gyro_mag']['name'] = 'magnitude of gyro.'
    db['subject'][i]['signal']['impression']['name'] = 'impression'
    # add parameter names in behaviour
    db['subject'][i]['behaviour']['state']['name'] = 'state'
    db['subject'][i]['behaviour']['performative_capacity_selfevaluation']['name'] = 'performative capacity ' \
                                                                                    'self-evaluation'
    db['subject'][i]['behaviour']['performation_quality_selfevaluation']['name'] = 'performation quality ' \
                                                                                   'self-evaluation'
    db['subject'][i]['behaviour']['performation_persuasion_selfevaluation']['name'] = 'performance persuasion ' \
                                                                                      'self-evaluation'
    db['subject'][i]['behaviour']['most_persuasion_segment_selfevaluation']['name'] = 'maximal persuasion segment'
    db['subject'][i]['behaviour']['less_persuasion_segment_selfevaluation']['name'] = 'minimal persuasion segment'
    db['subject'][i]['behaviour']['hardest_segment']['name'] = 'the hardest persuasion segment'
    db['subject'][i]['behaviour']['easiest_segment']['name'] = 'the easiest persuasion segment'
    db['subject'][i]['behaviour']['pleasant_segment']['name'] = 'the most pleasant segment'
    db['subject'][i]['behaviour']['unpleasant_segment']['name'] = 'the most unpleasant segment'
    db['subject'][i]['behaviour']['is_pause_performation_dialoque']['name'] = 'performation dialoque in pause?'
    db['subject'][i]['behaviour']['is_recipient_feedback']['name'] = 'recipient feedback exist?'
    db['subject'][i]['behaviour']['is_recipient_respiratory_feedback']['name'] = 'recipient respiratory feedback exist?'
    db['subject'][i]['behaviour']['is_recipient_eyecontact']['name'] = 'eye contact?'
    db['subject'][i]['behaviour']['is_performer_respiratory']['name'] = 'performer focus on its own breathing?'
    db['subject'][i]['behaviour']['device_disturbing']['name'] = 'A-V device manipulation distruption?'
    db['subject'][i]['behaviour']['recipient_feedback_form']['name'] = 'recipient feedback form'
    db['subject'][i]['behaviour']['pause_performation_form']['name'] = 'pause performation form'
    db['subject'][i]['behaviour']['respiratory_feedback_reasoning']['name'] = 'respiratory feedback reasoning'
    db['subject'][i]['behaviour']['eye_contact_reasoning']['name'] = 'eye contact reasoning'
    db['subject'][i]['behaviour']['persuasion_segment_selfevaluation_reasoning']['name'] = 'persuasion ' \
                                                                                           'segment ' \
                                                                                           'self-evaluation reasoning'

    # add parameter names in anotation
    db['subject'][i]['annotation']['is_persuasion']['name'] = 'persuasion detected'
    db['subject'][i]['annotation']['emotion']['name'] = 'emotion'
    # add parameter names in analysis
    db['subject'][i]['analysis']['arousal_is_start']['name'] = 'start of arousal'
    db['subject'][i]['analysis']['arousal_is_end']['name'] = 'end of arousal'
    db['subject'][i]['analysis']['arousal_is_high']['name'] = 'arousal > 95%'
    db['subject'][i]['analysis']['arousal_is_low']['name'] = 'arousal < 5%'
    db['subject'][i]['analysis']['arousal_activity_mean_numeric']['name'] = 'arousal mean'
    db['subject'][i]['analysis']['arousal_activity_mean_verbal']['name'] = 'arousal mean'
    db['subject'][i]['analysis']['arousal_activity_groupmean_numeric']['name'] = 'arousal group mean'
    db['subject'][i]['analysis']['arousal_activity_groupmean_verbal']['name'] = 'arousal group mean'
    db['subject'][i]['analysis']['valence_activity_mean_numeric']['name'] = 'valence mean'
    db['subject'][i]['analysis']['valence_activity_mean_verbal']['name'] = 'valence mean'
    db['subject'][i]['analysis']['valence_activity_groupmean_numeric']['name'] = 'valence group mean'
    db['subject'][i]['analysis']['valence_activity_groupmean_verbal']['name'] = 'valence group mean'
    db['subject'][i]['analysis']['hr_smooth_activity_mean']['name'] = 'mean heart rate'
    db['subject'][i]['analysis']['acc_activity_amount']['name'] = 'amount of acc.'
    db['subject'][i]['analysis']['acc_total_amount']['name'] = 'amount of acc.'
    db['subject'][i]['analysis']['gyro_activity_amount']['name'] = 'amount of gyro.'
    db['subject'][i]['analysis']['gyro_total_amount']['name'] = 'amount of gyro'
    db['subject'][i]['analysis']['hr_activity_correlation']['name'] = 'heart rate corr.'
    db['subject'][i]['analysis']['hr_total_correlation']['name'] = 'heart rate corr.'
    db['subject'][i]['analysis']['temp_hand_activity_correlation']['name'] = 'hand temp. corr.'
    db['subject'][i]['analysis']['temp_hand_total_correlation']['name'] = 'hand temp. corr.'
    db['subject'][i]['analysis']['temp_head_activity_correlation']['name'] = 'head temp. corr.'
    db['subject'][i]['analysis']['temp_head_total_correlation']['name'] = 'head temp. corr.'
    db['subject'][i]['analysis']['temp_ear_activity_correlation']['name'] = 'ear temp. corr.'
    db['subject'][i]['analysis']['temp_ear_total_correlation']['name'] = 'ear temp. corr.'
    db['subject'][i]['analysis']['eeg_af7_alpha_activity_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_af8_alpha_activity_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_tp9_alpha_activity_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_tp10_alpha_activity_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_af7_alpha_total_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_af8_alpha_total_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_tp9_alpha_total_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_tp10_alpha_total_energy']['name'] = 'energy in alpha'
    db['subject'][i]['analysis']['eeg_af7_beta_activity_energy']['name'] = 'energy in beta'
    db['subject'][i]['analysis']['eeg_af8_beta_activity_energy']['name'] = 'energy in beta'
    db['subject'][i]['analysis']['eeg_tp9_beta_activity_energy']['name'] = 'energy in beta'
    db['subject'][i]['analysis']['eeg_tp10_beta_activity_energy']['name'] = 'energy in beta'
    db['subject'][i]['analysis']['eeg_af7_beta_total_energy']['name'] = 'energy in beta'
    db['subject'][i]['analysis']['eeg_af8_beta_total_energy']['name'] = 'energy in beta'
    db['subject'][i]['analysis']['eeg_tp9_beta_total_energy']['name'] = 'energy in beta'
    db['subject'][i]['analysis']['eeg_tp10_beta_total_energy']['name'] = 'energy in beta'

    # add parameter description
    # add parameter description in record
    db['subject'][i]['record']['timestamp']['description'] = 'timestamp'
    db['subject'][i]['record']['res']['description'] = 'respiration'
    db['subject'][i]['record']['res_amp']['description'] = 'respiration amplitude'
    db['subject'][i]['record']['res_freq']['description'] = 'respiration frequency'
    db['subject'][i]['record']['temp_head']['description'] = 'head temperature'
    db['subject'][i]['record']['temp_hand']['description'] = 'hand temperature'
    db['subject'][i]['record']['temp_ear']['description'] = 'ear temperature'
    db['subject'][i]['record']['hr']['description'] = 'heart rate'
    db['subject'][i]['record']['eeg_tp9']['description'] = 'electroencephalogram TP9 electrode'
    db['subject'][i]['record']['eeg_af7']['description'] = 'electroencephalogram AF7 electrode'
    db['subject'][i]['record']['eeg_af8']['description'] = 'electroencephalogram AF8 electrode'
    db['subject'][i]['record']['eeg_tp10']['description'] = 'electroencephalogram TP10 electrode'
    db['subject'][i]['record']['acc_x']['description'] = 'linear acceleration in forward - backward direction'
    db['subject'][i]['record']['acc_y']['description'] = 'linear acceleration in left - right direction'
    db['subject'][i]['record']['acc_z']['description'] = 'linear acceleration in up - down direction'
    db['subject'][i]['record']['gyro_x']['description'] = 'rotation acceleration in roll'
    db['subject'][i]['record']['gyro_y']['description'] = 'rotation acceleration in pitch'
    db['subject'][i]['record']['gyro_z']['description'] = 'rotation acceleration in yaw'
    db['subject'][i]['record']['arousal']['description'] = 'arousal'
    db['subject'][i]['record']['valence']['description'] = 'valence'
    db['subject'][i]['record']['marker']['description'] = 'marker'
    # add parameter description in signal
    db['subject'][i]['signal']['hr_smooth']['description'] = 'filtered (smoothed) heart rate'
    db['subject'][i]['signal']['hr_smooth_derivation']['description'] = 'speed of heart rate changes'
    db['subject'][i]['signal']['res_volume']['description'] = 'respiratory volume'
    db['subject'][i]['signal']['acc_mag']['description'] = 'magnitude of linear acceleration'
    db['subject'][i]['signal']['gyro_mag']['description'] = 'magnitude of rotation acceleration'
    db['subject'][i]['signal']['impression']['description'] = 'impression being performed or perceived'
    # add parameter description in behaviour
    db['subject'][i]['behaviour']['state']['description'] = 'mental state of subject'
    db['subject'][i]['behaviour']['performative_capacity_selfevaluation']['description'] = 'subjective evaluation of performative capacity'
    db['subject'][i]['behaviour']['performation_quality_selfevaluation']['description'] = 'subjective evaluation of performance quality'
    db['subject'][i]['behaviour']['performation_persuasion_selfevaluation']['description'] = 'subjective evaluation of performance persuasion'
    db['subject'][i]['behaviour']['most_persuasion_segment_selfevaluation']['description'] = 'subjective evaluation of the maximal persuasion segment'
    db['subject'][i]['behaviour']['less_persuasion_segment_selfevaluation']['description'] = 'subjective evaluation of the mininal persuasion segment'
    db['subject'][i]['behaviour']['hardest_segment']['description'] = 'subjective evaluation of the hardest persuasion segment'
    db['subject'][i]['behaviour']['easiest_segment']['description'] = 'subjective evaluation of the easiest persuasion segment'
    db['subject'][i]['behaviour']['pleasant_segment']['description'] = 'subjective evaluation of the most pleasant segment'
    db['subject'][i]['behaviour']['unpleasant_segment']['description'] = 'subjective evaluation of the most unpleasant segment'
    db['subject'][i]['behaviour']['is_pause_performation_dialoque']['description'] = 'does dialoque exist during pause segment?'
    db['subject'][i]['behaviour']['is_recipient_feedback']['description'] = 'does performer react on recipient somehow?'
    db['subject'][i]['behaviour']['is_recipient_respiratory_feedback']['description'] = 'does performer reacts on ' \
                                                                                        'recipient respiratory changes?'
    db['subject'][i]['behaviour']['is_recipient_eyecontact']['description'] = 'does performer keep eye contact with recipient'
    db['subject'][i]['behaviour']['is_performer_respiratory']['description'] = 'does performer focus on its own ' \
                                                                               'breathing?'
    db['subject'][i]['behaviour']['device_disturbing']['description'] = 'does A-V device manipulation distrupt performer?'
    db['subject'][i]['behaviour']['recipient_feedback_form']['description'] = 'the way performer feels recipient feedback'
    db['subject'][i]['behaviour']['pause_performation_form']['description'] = 'the way performer performed pause '
    db['subject'][i]['behaviour']['respiratory_feedback_reasoning']['description'] = 'the way performer observes recipient respiratory changes'
    db['subject'][i]['behaviour']['eye_contact_reasoning']['description'] = 'the way performer keep eye contact with recipient'
    db['subject'][i]['behaviour']['persuasion_segment_selfevaluation_reasoning']['description'] = 'reasoning of maximal/minimal persuasion segment'
    # add parameter description in annotation
    db['subject'][i]['annotation']['is_persuasion']['description'] = 'persuasion detected'
    db['subject'][i]['annotation']['emotion']['description'] = 'emotion being performer or perceived'
    # add parameter description in analysis
    db['subject'][i]['analysis']['arousal_is_start']['description'] = 'start of arousal detected'
    db['subject'][i]['analysis']['arousal_is_end']['description'] = 'end of arousal detected'
    db['subject'][i]['analysis']['arousal_is_high']['description'] = 'arousal > 95% detected'
    db['subject'][i]['analysis']['arousal_is_low']['description'] = 'arousal < 5% detected'
    db['subject'][i]['analysis']['arousal_activity_mean_numeric']['description'] = 'mean value of arousal during the activity'
    db['subject'][i]['analysis']['arousal_activity_mean_verbal']['description'] = 'verbal equivalent of mean value of arousal during the activity'
    db['subject'][i]['analysis']['arousal_activity_groupmean_numeric']['description'] = 'group mean of arousals during the activity'
    db['subject'][i]['analysis']['arousal_activity_groupmean_verbal']['description'] = 'verbal equivalent of group mean of arousal during activity'
    db['subject'][i]['analysis']['valence_activity_mean_numeric']['description'] = 'mean value of valence during the activity'
    db['subject'][i]['analysis']['valence_activity_mean_verbal']['description'] = 'verbal equivalent of mean value of valence during the activity'
    db['subject'][i]['analysis']['valence_activity_groupmean_numeric']['description'] = 'group mean of valences during the activity'
    db['subject'][i]['analysis']['valence_activity_groupmean_verbal']['description'] = 'verbal equivalent of group mean of valence during activity'
    db['subject'][i]['analysis']['hr_smooth_activity_mean']['description'] = 'mean value of heart rate during the activity'
    db['subject'][i]['analysis']['acc_activity_amount']['description'] = 'amount of linear acceleration during activity'
    db['subject'][i]['analysis']['acc_total_amount']['description'] = 'total amount of linear acceleration'
    db['subject'][i]['analysis']['gyro_activity_amount']['description'] = 'amount of rotation during activity'
    db['subject'][i]['analysis']['gyro_total_amount']['description'] = 'total amount of rotation'
    db['subject'][i]['analysis']['hr_activity_correlation']['description'] = 'correlation between P-s and R-s heart rate during activity'
    db['subject'][i]['analysis']['hr_total_correlation']['description'] = 'total correlation between P-s and R-s heart rate'
    db['subject'][i]['analysis']['temp_hand_activity_correlation']['description'] = 'correlation between P-s and R-s hand temperature during activity'
    db['subject'][i]['analysis']['temp_hand_total_correlation']['description']= 'total correlation between P-s and R-s hand temperature'
    db['subject'][i]['analysis']['temp_head_activity_correlation']['description'] = 'correlation between P-s and R-s head temperature during activity'
    db['subject'][i]['analysis']['temp_head_total_correlation']['description'] = 'total correlation between P-s and R-s head temperature'
    db['subject'][i]['analysis']['temp_ear_activity_correlation']['description'] = 'correlation between P-s and R-s ear temperature during activity'
    db['subject'][i]['analysis']['temp_ear_total_correlation']['description'] = 'total correlation between P-s and R-s ear temperature'
    db['subject'][i]['analysis']['eeg_af7_alpha_activity_energy']['description'] = 'energy of AF7 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_af8_alpha_activity_energy']['description'] = 'energy of AF8 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_tp9_alpha_activity_energy']['description'] = 'energy of TP9 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_tp10_alpha_activity_energy']['description'] = 'energy of TP10 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_af7_alpha_total_energy']['description'] = 'total energy of AF7 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_af8_alpha_total_energy']['description'] = 'total energy of AF8 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_tp9_alpha_total_energy']['description'] = 'total energy of TP9 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_tp10_alpha_total_energy']['description'] = 'total energy of TP10 EEG in alpha band during activity'
    db['subject'][i]['analysis']['eeg_af7_beta_activity_energy']['description'] = 'energy of AF7 EEG in beta band during activity'
    db['subject'][i]['analysis']['eeg_af8_beta_activity_energy']['description'] = 'energy of AF8 EEG in beta band during activity'
    db['subject'][i]['analysis']['eeg_tp9_beta_activity_energy']['description'] = 'energy of TP9 EEG in beta band during activity'
    db['subject'][i]['analysis']['eeg_tp10_beta_activity_energy']['description'] = 'energy of TP10 EEG in beta band during activity'
    db['subject'][i]['analysis']['eeg_af7_beta_total_energy']['description'] = 'total energy of AF7 EEG in beta band during activity'
    db['subject'][i]['analysis']['eeg_af8_beta_total_energy']['description'] = 'total energy of AF8 EEG in beta band during activity'
    db['subject'][i]['analysis']['eeg_tp9_beta_total_energy']['description'] = 'total energy of TP9 EEG in beta band during activity'
    db['subject'][i]['analysis']['eeg_tp10_beta_total_energy']['description'] = 'total energy of TP10 EEG in beta band during activity'

    # add parameter units
    # add parameter units in record
    db['subject'][i]['record']['timestamp']['unit'] = '[s]'
    db['subject'][i]['record']['res']['unit'] = '[mV]'
    db['subject'][i]['record']['res_amp']['unit'] = '[-]'
    db['subject'][i]['record']['res_freq']['unit'] = '[cpm]'
    db['subject'][i]['record']['temp_head']['unit'] = '['+u'\N{DEGREE SIGN}'+'C]'
    db['subject'][i]['record']['temp_hand']['unit'] = '['+u'\N{DEGREE SIGN}'+'C]'
    db['subject'][i]['record']['temp_ear']['unit'] = '['+u'\N{DEGREE SIGN}'+'C]'
    db['subject'][i]['record']['hr']['unit'] = '[BPM]'
    db['subject'][i]['record']['eeg_tp9']['unit'] = '[uV]'
    db['subject'][i]['record']['eeg_af7']['unit'] = '[uV]'
    db['subject'][i]['record']['eeg_af8']['unit'] = '[uV]'
    db['subject'][i]['record']['eeg_tp10']['unit'] = '[uV]'
    db['subject'][i]['record']['acc_x']['unit'] = '[g]'
    db['subject'][i]['record']['acc_y']['unit'] = '[g]'
    db['subject'][i]['record']['acc_z']['unit'] = '[g]'
    db['subject'][i]['record']['gyro_x']['unit'] = '[deg./s]'
    db['subject'][i]['record']['gyro_y']['unit'] = '[deg./s]'
    db['subject'][i]['record']['gyro_z']['unit'] = '[deg./s]'
    db['subject'][i]['record']['arousal']['unit'] = '[%]'
    db['subject'][i]['record']['valence']['unit'] = '[%]'
    db['subject'][i]['record']['marker']['unit'] = '[%]'
    # add parameter units in signal
    db['subject'][i]['signal']['hr_smooth']['unit'] = '[BPM]'
    db['subject'][i]['signal']['hr_smooth_derivation']['unit'] = '[BPM/s]'
    db['subject'][i]['signal']['res_volume']['unit'] = '[-]'
    db['subject'][i]['signal']['acc_mag']['unit'] = '[g]'
    db['subject'][i]['signal']['gyro_mag']['unit'] = '[deg./s]'
    db['subject'][i]['signal']['impression']['unit'] = '[%]'
    # add parameter units in behaviour
    db['subject'][i]['behaviour']['state']['unit'] = '-'
    db['subject'][i]['behaviour']['performative_capacity_selfevaluation']['unit'] = '-'
    db['subject'][i]['behaviour']['performation_quality_selfevaluation']['unit'] = '-'
    db['subject'][i]['behaviour']['performation_persuasion_selfevaluation']['unit'] = '-'
    db['subject'][i]['behaviour']['most_persuasion_segment_selfevaluation']['unit'] = '-'
    db['subject'][i]['behaviour']['less_persuasion_segment_selfevaluation']['unit'] = '-'
    db['subject'][i]['behaviour']['hardest_segment']['unit'] = '-'
    db['subject'][i]['behaviour']['easiest_segment']['unit'] = '-'
    db['subject'][i]['behaviour']['pleasant_segment']['unit'] = '-'
    db['subject'][i]['behaviour']['unpleasant_segment']['unit'] = '-'
    db['subject'][i]['behaviour']['is_pause_performation_dialoque']['unit'] = '-'
    db['subject'][i]['behaviour']['is_recipient_feedback']['unit'] = '-'
    db['subject'][i]['behaviour']['is_recipient_respiratory_feedback']['unit'] = '-'
    db['subject'][i]['behaviour']['is_recipient_eyecontact']['unit'] = '-'
    db['subject'][i]['behaviour']['is_performer_respiratory']['unit'] = '-'
    db['subject'][i]['behaviour']['device_disturbing']['unit'] = '-'
    db['subject'][i]['behaviour']['recipient_feedback_form']['unit'] = '-'
    db['subject'][i]['behaviour']['pause_performation_form']['unit'] = '-'
    db['subject'][i]['behaviour']['respiratory_feedback_reasoning']['unit'] = '-'
    db['subject'][i]['behaviour']['eye_contact_reasoning']['unit'] = '-'
    db['subject'][i]['behaviour']['persuasion_segment_selfevaluation_reasoning']['unit'] = '-'
    # add parameter units in anotation
    db['subject'][i]['annotation']['is_persuasion']['unit'] = '[boolean]'
    db['subject'][i]['annotation']['emotion']['unit'] = '[-]'
    # add parameter units in analysis
    db['subject'][i]['analysis']['arousal_is_start']['unit'] = '[boolean]'
    db['subject'][i]['analysis']['arousal_is_end']['unit'] = '[boolean]'
    db['subject'][i]['analysis']['arousal_is_high']['unit'] = '[boolean]'
    db['subject'][i]['analysis']['arousal_is_low']['unit'] = '[boolean]'
    db['subject'][i]['analysis']['arousal_activity_mean_numeric']['unit'] = '[%]'
    db['subject'][i]['analysis']['arousal_activity_mean_verbal']['unit'] = '[-]'
    db['subject'][i]['analysis']['arousal_activity_groupmean_numeric']['unit'] = '[%]'
    db['subject'][i]['analysis']['arousal_activity_groupmean_verbal']['unit'] = '[-]'
    db['subject'][i]['analysis']['valence_activity_mean_numeric']['unit'] = '[%]'
    db['subject'][i]['analysis']['valence_activity_mean_verbal']['unit'] = '[-]'
    db['subject'][i]['analysis']['valence_activity_groupmean_numeric']['unit'] = '[%]'
    db['subject'][i]['analysis']['valence_activity_groupmean_verbal']['unit'] = '[-]'
    db['subject'][i]['analysis']['hr_smooth_activity_mean']['unit'] = '[BPM]'
    db['subject'][i]['analysis']['acc_activity_amount']['unit'] = '[g]'
    db['subject'][i]['analysis']['acc_total_amount']['unit'] = '[g]'
    db['subject'][i]['analysis']['gyro_activity_amount']['unit'] = '[deg./s]'
    db['subject'][i]['analysis']['gyro_total_amount']['unit'] = '[°/s]'
    db['subject'][i]['analysis']['hr_activity_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['hr_total_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['temp_hand_activity_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['temp_hand_total_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['temp_head_activity_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['temp_head_total_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['temp_ear_activity_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['temp_ear_total_correlation']['unit'] = '[-]'
    db['subject'][i]['analysis']['eeg_af7_alpha_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_af8_alpha_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp9_alpha_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp10_alpha_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_af7_alpha_total_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_af8_alpha_total_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp9_alpha_total_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp10_alpha_total_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_af7_beta_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_af8_beta_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp9_beta_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp10_beta_activity_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_af7_beta_total_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_af8_beta_total_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp9_beta_total_energy']['unit'] = '[V^2/Hz]'
    db['subject'][i]['analysis']['eeg_tp10_beta_total_energy']['unit'] = '[V^2/Hz]'

# save database on local drive
with open('db.pickle', 'wb') as handle:
    pickle.dump(db, handle)


