print('STARTING...')
exec(open("load_biosignals.py").read())
print('biosignals loaded')
exec(open("incorporate_annotation.py").read())
print('annotation added')
exec(open("incorporate_device.py").read())
print('device added')
exec(open("incorporate_description.py").read())
print('description added')
exec(open("evaluate_signals.py").read())
print('signals evaluated')
exec(open("evaluate_behaviour.py", encoding="utf8").read())
print('behaviour evaluated')
exec(open("analyse.py").read())
print('analyse provided')
exec(open("add_units_and_explanation.py").read())
print('units and explanation added')
exec(open("estimate_persuasion.py").read())
print('persuasion estimated')
exec(open("show_results.py").read())
print('results shown')
print('DONE. SEE OUTPUT IN WORKING DIR.')

